baseURL = 'http://blog.cyberpsych0si.is/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "terminal"

[params]
    color = "blue"
    centerTheme = true

[module]
  # this is needed when you fetch the theme as a submodule to your repo.
  # replacements = "github.com/panr/hugo-theme-terminal -> themes/terminal"
[[module.imports]]
  path = 'github.com/thallosaurus/hugo-theme-terminal'